cd %~dp0
REM If the PATH is wrong, use your 'Developer Command Prompt for VS'
set PATH=%ProgramFiles(X86)%\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.23.27911\bin\HostX86\x86;%ProgramFiles(X86)%\Microsoft Visual Studio\2019\Preview\Common7\IDE\VC\VCPackages;%ProgramFiles(X86)%\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\TestWindow;%ProgramFiles(X86)%\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;%ProgramFiles(X86)%\Microsoft Visual Studio\2019\Preview\MSBuild\Current\bin\Roslyn;%ProgramFiles(X86)%\Microsoft Visual Studio\2019\Preview\Team Tools\Performance Tools;%ProgramFiles(X86)%\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;%ProgramFiles(X86)%\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools\;%ProgramFiles(X86)%\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\FSharp\;%ProgramFiles(X86)%\Windows Kits\10\bin\10.0.18362.0\x86;%ProgramFiles(X86)%\Windows Kits\10\bin\x86;%ProgramFiles(X86)%\Microsoft Visual Studio\2019\Preview\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework\v4.0.30319;%ProgramFiles(X86)%\Microsoft Visual Studio\2019\Preview\Common7\IDE\;%ProgramFiles(X86)%\Microsoft Visual Studio\2019\Preview\Common7\Tools\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;%ProgramFiles(X86)%\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\010 Editor;C:\Program Files\Firebird\Firebird_3_0;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;%ProgramFiles(X86)%\Paragon Software\Paragon ExtFS for Windows;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.3.0\;%ProgramFiles(X86)%\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;%userprofile%\AppData\Local\Microsoft\WindowsApps;%userprofile%\AppData\Roaming\npm;%userprofile%\.dotnet\tools;%userprofile%\AppData\Local\Microsoft\WindowsApps;%userprofile%\AppData\Local\Programs\Microsoft VS Code\bin;;%ProgramFiles(X86)%\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;%ProgramFiles(X86)%\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
echo off
cls
REM csc "%1" -target:library -lib:..\bin\Debug\,..\bin\debug\x64 -reference:MangaUnhost.exe -reference:HtmlAgilityPack.dll -reference:CefSharp.dll -reference:CefSharp.OffScreen.dll -reference:CefSharp.Core.dll
csc "%1" -target:library -lib:..\bin\Debug\,..\bin\debug\x64,%userprofile%\.nuget\packages\htmlagilitypack\1.11.12\lib\Net45 -reference:HtmlAgilityPack.dll -reference:MangaUnhost.exe -reference:CefSharp.dll -reference:CefSharp.OffScreen.dll -reference:CefSharp.Core.dll
if exist "..\bin\Debug\Plugins" (
move /y "%~n1.dll" "..\bin\Debug\Plugins"
)